### ISSUE TITLE
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-0f7ean85/imagekit Storing debug log for failure in /home/user/.pip/pip.log error ?

### ISSUE THREAD

**Issue by pratyush247** [andyalam/django_ig#2]
During installing of requirements.txt file with the use of python3 and pip3 terminal is throwing this error :
pip3 install -r requirements.txt
Downloading/unpacking django-annoying==0.8.1 (from -r requirements.txt (line 1))
  Downloading django-annoying-0.8.1.tar.gz
  Running setup.py (path:/tmp/pip-build-0f7ean85/django-annoying/setup.py) egg_info for package django-annoying
    
Downloading/unpacking channels==0.17.3 (from -r requirements.txt (line 2))
  Downloading channels-0.17.3-py2.py3-none-any.whl (53kB): 53kB downloaded
Downloading/unpacking Django==1.10.3 (from -r requirements.txt (line 3))
  Downloading Django-1.10.3-py2.py3-none-any.whl (6.8MB): 6.8MB downloaded
Downloading/unpacking django-imagekit==3.3 (from -r requirements.txt (line 4))
  Downloading django-imagekit-3.3.tar.gz (56kB): 56kB downloaded
  Running setup.py (path:/tmp/pip-build-0f7ean85/django-imagekit/setup.py) egg_info for package django-imagekit
    
    no previously-included directories found matching 'tests'
Downloading/unpacking imagekit==1.0.0 (from -r requirements.txt (line 5))
  Downloading imagekit-1.0.0.tar.gz
  Running setup.py (path:/tmp/pip-build-0f7ean85/imagekit/setup.py) egg_info for package imagekit
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-0f7ean85/imagekit/setup.py", line 21, in <module>
        with open('LICENSE') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'LICENSE'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-0f7ean85/imagekit/setup.py", line 21, in <module>

    with open('LICENSE') as f:

FileNotFoundError: [Errno 2] No such file or directory: 'LICENSE'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-0f7ean85/imagekit
Storing debug log for failure in /home/pratyush/.pip/pip.log

**Comment by andyalam** [comment]
I've updated the repo with a new requirements.txt, try to use that. This project also requires python3 and pip3, so make sure you're using the correct versions on everything.

**Comment by andyalam** [comment]
The requirements.txt is updated now, do a pull and try again. If issues still persist open another issue on the repo please, thanks!

**Comment by pratyush247** [comment]
Great!
