### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by Butonix** [andyalam/django_ig#4]
Hello
Please write detailed installation and start-up instructions.
Thank you very much for your efforts.
Yours faithfully

**Comment by Butonix** [comment]
Error: pg_config executable not found.

    Please add the directory containing pg_config to the PATH
    or specify the full executable path with the option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\D0CE~1\AppData\Local\Temp\pip-build-6r0h5h6j\psycopg2\

**Comment by andyalam** [comment]
I'm copy pasting the email you sent me below:

> Error: pg_config executable not found.
> 
> Please add the directory containing pg_config to the PATH
> or specify the full executable path with the option:
> 
>     python setup.py build_ext --pg-config /path/to/pg_config build ...
> 
> or with the pg_config option in 'setup.cfg'.

You're setting up postgres/psycopg2 incorrectly, or don't have it at all. Next time please google before opening issues on the repo. Below are some links off of google from your error:

[1](https://stackoverflow.com/questions/11618898/pg-config-executable-not-found)
[2](https://stackoverflow.com/questions/5420789/how-to-install-psycopg2-with-pip-on-python)
